name: GitHub Actions Demo
on: ["push"]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-varsion: [20.x]
    steps:
      - name: install modules
        run: npm install
      - name: build project
        run: npm run build
